apiVersion: agentengine.cloud.google.com/v1
kind: AgentService
metadata:
  name: marketing-agent
  namespace: default
spec:
  image: gcr.io/${GCP_PROJECT}/marketing-agent:latest
  env:
    - name: GCP_PROJECT
      value: ${GCP_PROJECT}
    - name: VERTEX_LOCATION
      value: ${VERTEX_LOCATION}
    - name: REGION
      value: ${REGION}
    - name: GCS_BUCKET
      value: ${GCS_BUCKET}
    - name: GEMINI_MODEL
      value: ${GEMINI_MODEL}
    - name: IMAGEN_MODEL
      value: ${IMAGEN_MODEL}
    - name: VEO_MODEL
      value: ${VEO_MODEL}
  resources:
    cpu: "2"
    memory: "4Gi"
  autoscaling:
    minReplicas: 1
    maxReplicas: 5
  iam:
    workloadIdentity: true
  ingress:
    public: true
  health:
    path: /healthz
    port: 8080